set = set()
nome = str(input('Diga seu nome ai meu bom:'))
idade = int(input('Diga sua idade ai meu bom:'))
sexo = str(input('Diga seu sexo ai meu bom:'))
set.add(nome)
set.add(idade)
set.add(sexo)
print(f'Que nome lindo voce tem {nome}!')
print(f'Voce e muito jovem ainda tem so {idade} anos po!')
print(f'Voce e {sexo} que legal!')